AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Image Upload and Processing with DevOps Automation

Globals:
  Function:
    Timeout: 10
    Runtime: python3.10
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        BUCKET_NAME: !Ref ImageBucket

Resources:

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "image-processing-bucket-${AWS::AccountId}-${AWS::Region}"


  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UploadFunction
      Handler: app.lambda_handler
      CodeUri: uploadimage/
      Runtime: python3.10
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UploadAPI:
          Type: Api
          Properties:
            Path: /uploadimage
            Method: post



  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3LogsSNSAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "${ImageBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "*"

Outputs:
  UploadAPIEndpoint:
    Description: "API Gateway endpoint to upload image"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/uploadimage"
