name: Deploy to AWS

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsDeploymentRole  # update this
          aws-region: us-east-1  # your AWS region

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://template.yaml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name image-processing-app \
            --capabilities CAPABILITY_IAM \
            --region us-east-1
