name: Deploy Serverless Image App

on:
  push:
    branches: [main]

env:
  BUCKET_NAME: my-serverless-artifacts-bucket
  STACK_NAME: serverless-image-app
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.1

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create S3 Bucket if not exists
        run: |
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket does not exist. Creating $BUCKET_NAME..."
            if [ "$AWS_REGION" == "us-east-1" ]; then
              aws s3api create-bucket \
                --bucket "$BUCKET_NAME"
            else
              aws s3api create-bucket \
                --bucket "$BUCKET_NAME" \
                --region "$AWS_REGION" \
                --create-bucket-configuration LocationConstraint="$AWS_REGION"
            fi
          else
            echo "Bucket $BUCKET_NAME already exists."
          fi

      - name: Build SAM App
        run: sam build

      - name: Deploy SAM App
        run: |
          sam deploy \
            --stack-name $STACK_NAME \
            --s3-bucket $BUCKET_NAME \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
