name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         with:
         role-to-assume: arn:aws:iam::339712737407:role/GitHubActionsDeploymentRole
         aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name image-processing-app \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-1

