name: Deploy to AWS using SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy SAM Stack

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or your region

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM app
        run: sam build

      - name: Deploy SAM app
        run: |
          sam deploy --stack-name image-processing-app \
                     --capabilities CAPABILITY_IAM \
                     --region us-east-1 \
                     --confirm-changeset \
                     --no-fail-on-empty-changeset
