name: Deploy SAM Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build SAM project
        run: sam build

      - name: Deploy SAM application
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name image-processing-app \
            --capabilities CAPABILITY_IAM \
            --resolve-s3

      - name: Upload frontend to S3
        run: |
          aws s3 cp frontend/index.html s3://image-frontend-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.AWS_REGION }}-image-processing-app/ --acl public-read
